/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module spi_exe_unit_3_rtl(i_rst, i_sclk, i_mosi, o_miso, i_cs);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire [10:0] _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire [1:0] \exe_unit1.BF ;
  wire [1:0] \exe_unit1.NF ;
  wire [1:0] \exe_unit1.SF ;
  wire [31:0] \exe_unit1.bf_pointer_main.counter ;
  wire [31:0] \exe_unit1.bf_pointer_main.i ;
  wire [3:0] \exe_unit1.bf_pointer_main.i_input ;
  wire [1:0] \exe_unit1.bf_pointer_main.o_pointer_local ;
  wire [2:0] \exe_unit1.crc3_main.crc ;
  wire [6:0] \exe_unit1.crc3_main.crc_tmp ;
  wire [31:0] \exe_unit1.crc3_main.i ;
  wire [3:0] \exe_unit1.crc3_main.i_data ;
  wire [3:0] \exe_unit1.crc3_main.i_poly ;
  wire [2:0] \exe_unit1.crc3_main.o_crc_local ;
  wire [2:0] \exe_unit1.crc3_main.poly_tmp ;
  wire [2:0] \exe_unit1.crc4_main.crc ;
  wire [6:0] \exe_unit1.crc4_main.crc_tmp ;
  wire [31:0] \exe_unit1.crc4_main.i ;
  wire [3:0] \exe_unit1.crc4_main.i_data ;
  wire [3:0] \exe_unit1.crc4_main.i_poly ;
  wire [2:0] \exe_unit1.crc4_main.o_crc_local ;
  wire [2:0] \exe_unit1.crc4_main.poly_tmp ;
  wire [3:0] \exe_unit1.gray_to_u2 ;
  wire [31:0] \exe_unit1.gray_to_u2_main.i ;
  wire [3:0] \exe_unit1.gray_to_u2_main.i_gray ;
  wire [3:0] \exe_unit1.gray_to_u2_main.o_result_local ;
  wire [3:0] \exe_unit1.i_argA ;
  wire [3:0] \exe_unit1.i_argB ;
  wire [3:0] \exe_unit1.i_oper ;
  wire [31:0] \exe_unit1.nf_pointer_main.counter ;
  wire [31:0] \exe_unit1.nf_pointer_main.i ;
  wire [3:0] \exe_unit1.nf_pointer_main.i_input ;
  wire [1:0] \exe_unit1.nf_pointer_main.o_pointer_local ;
  wire [1:0] \exe_unit1.o_BF ;
  wire [1:0] \exe_unit1.o_NF ;
  wire [1:0] \exe_unit1.o_PF ;
  wire [1:0] \exe_unit1.o_SF ;
  wire [2:0] \exe_unit1.o_crc3 ;
  wire [2:0] \exe_unit1.o_crc4 ;
  wire [3:0] \exe_unit1.o_result ;
  wire [3:0] \exe_unit1.ones_counter ;
  wire [31:0] \exe_unit1.ones_counter_main.i ;
  wire [3:0] \exe_unit1.ones_counter_main.i_argA_local ;
  wire [3:0] \exe_unit1.ones_counter_main.i_argB_local ;
  wire [3:0] \exe_unit1.ones_counter_main.o_result_local ;
  wire [3:0] \exe_unit1.sf_pointer_main.i_input ;
  wire [1:0] \exe_unit1.sf_pointer_main.o_pointer_local ;
  wire [1:0] \exe_unit1.thermometer_code ;
  wire [31:0] \exe_unit1.thermometer_code_main.i ;
  wire [3:0] \exe_unit1.thermometer_code_main.i_thermo ;
  wire [1:0] \exe_unit1.thermometer_code_main.o_result_local ;
  wire [3:0] \exe_unit1.thermometer_decode ;
  wire [31:0] \exe_unit1.thermometer_decoder_main.i ;
  wire [3:0] \exe_unit1.thermometer_decoder_main.i_nkb ;
  wire [14:0] \exe_unit1.thermometer_decoder_main.o_result_local ;
  wire [3:0] \exe_unit1.u2_to_u1 ;
  wire [3:0] \exe_unit1.u2_to_u1_main.i_argA_local ;
  wire [3:0] \exe_unit1.u2_to_u1_main.o_result_local ;
  input [2:0] i_cs;
  input i_mosi;
  input i_rst;
  input i_sclk;
  output o_miso;
  reg [3:0] reg_argA;
  reg [3:0] reg_argB;
  reg [3:0] reg_flags;
  reg [3:0] reg_oper;
  reg [3:0] reg_results;
  wire [3:0] s_argA;
  wire [3:0] s_argA_next;
  wire [3:0] s_argB;
  wire [3:0] s_argB_next;
  reg s_bit;
  wire s_bit_next;
  wire [19:0] s_data;
  wire [3:0] s_flags;
  wire [3:0] s_flags_next;
  wire s_inter;
  wire [3:0] s_oper;
  wire [3:0] s_oper_next;
  wire [3:0] s_results;
  wire [3:0] s_results_next;
  reg [3:0] s_state;
  wire [3:0] s_state_next;
  wire s_transfer;
  wire s_watchdog_we;
  wire s_wrt;
  wire [19:0] s_wyniki;
  wire \shift_out.i_bit ;
  wire \shift_out.i_clk_p ;
  wire [19:0] \shift_out.i_data ;
  wire \shift_out.i_en ;
  wire \shift_out.i_rst_n ;
  wire \shift_out.i_wrt ;
  wire \shift_out.o_bit ;
  wire [19:0] \shift_out.o_data ;
  reg [19:0] \shift_out.s_shifter ;
  wire [19:0] \shift_out.s_shifter_next ;
  wire \watchdog.i_clk_p ;
  wire [4:0] \watchdog.i_cycles ;
  wire \watchdog.i_rst_n ;
  wire \watchdog.i_we ;
  wire \watchdog.o_inter ;
  reg [4:0] \watchdog.s_count ;
  wire [4:0] \watchdog.s_count_next ;
  reg [4:0] \watchdog.s_cycles ;
  wire [4:0] \watchdog.s_cycles_next ;
  assign _0000_ = ~s_state[1];
  assign _0001_ = ~s_state[0];
  assign _0002_ = ~s_state[3];
  assign _0003_ = ~s_state[2];
  assign _0004_ = ~i_cs[2];
  assign _0005_ = _0000_ & _0001_;
  assign _0006_ = _0002_ & s_state[2];
  assign s_wrt = _0005_ & _0006_;
  assign _0007_ = _0002_ & _0003_;
  assign _0008_ = s_state[3] | s_state[2];
  assign _0009_ = s_state[0] & _0004_;
  assign _0010_ = _0001_ | i_cs[2];
  assign _0011_ = i_cs[1] & i_cs[0];
  assign _0012_ = ~_0011_;
  assign _0013_ = _0009_ & _0011_;
  assign _0014_ = _0010_ | _0012_;
  assign _0015_ = _0007_ & _0013_;
  assign _0016_ = _0008_ | _0014_;
  assign s_watchdog_we = _0000_ & _0015_;
  assign s_data[0] = reg_flags[0] & s_wrt;
  assign s_data[1] = reg_flags[1] & s_wrt;
  assign s_data[2] = reg_flags[2] & s_wrt;
  assign s_data[3] = reg_flags[3] & s_wrt;
  assign s_data[4] = reg_results[0] & s_wrt;
  assign s_data[5] = reg_results[1] & s_wrt;
  assign s_data[6] = reg_results[2] & s_wrt;
  assign s_data[7] = reg_results[3] & s_wrt;
  assign s_data[8] = reg_oper[0] & s_wrt;
  assign s_data[9] = reg_oper[1] & s_wrt;
  assign s_data[10] = reg_oper[2] & s_wrt;
  assign s_data[11] = reg_oper[3] & s_wrt;
  assign s_data[12] = reg_argB[0] & s_wrt;
  assign s_data[13] = reg_argB[1] & s_wrt;
  assign s_data[14] = reg_argB[2] & s_wrt;
  assign s_data[15] = reg_argB[3] & s_wrt;
  assign s_data[16] = reg_argA[0] & s_wrt;
  assign s_data[17] = reg_argA[1] & s_wrt;
  assign s_data[18] = reg_argA[2] & s_wrt;
  assign s_data[19] = reg_argA[3] & s_wrt;
  assign _0017_ = _0000_ | _0008_;
  assign _0018_ = ~_0017_;
  assign _0019_ = _0001_ & _0018_;
  assign _0020_ = s_state[0] | _0017_;
  assign _0021_ = s_wyniki[8] & _0019_;
  assign _0022_ = reg_oper[0] & _0020_;
  assign s_oper_next[0] = _0021_ | _0022_;
  assign _0023_ = s_wyniki[9] & _0019_;
  assign _0024_ = reg_oper[1] & _0020_;
  assign s_oper_next[1] = _0023_ | _0024_;
  assign _0025_ = s_wyniki[10] & _0019_;
  assign _0026_ = reg_oper[2] & _0020_;
  assign s_oper_next[2] = _0025_ | _0026_;
  assign _0027_ = s_wyniki[11] & _0019_;
  assign _0028_ = reg_oper[3] & _0020_;
  assign s_oper_next[3] = _0027_ | _0028_;
  assign _0029_ = s_wyniki[12] & _0019_;
  assign _0030_ = reg_argB[0] & _0020_;
  assign s_argB_next[0] = _0029_ | _0030_;
  assign _0031_ = s_wyniki[13] & _0019_;
  assign _0032_ = reg_argB[1] & _0020_;
  assign s_argB_next[1] = _0031_ | _0032_;
  assign _0033_ = s_wyniki[14] & _0019_;
  assign _0034_ = reg_argB[2] & _0020_;
  assign s_argB_next[2] = _0033_ | _0034_;
  assign _0035_ = s_wyniki[15] & _0019_;
  assign _0036_ = reg_argB[3] & _0020_;
  assign s_argB_next[3] = _0035_ | _0036_;
  assign _0037_ = s_wyniki[16] & _0019_;
  assign _0038_ = reg_argA[0] & _0020_;
  assign s_argA_next[0] = _0037_ | _0038_;
  assign _0039_ = s_wyniki[17] & _0019_;
  assign _0040_ = reg_argA[1] & _0020_;
  assign s_argA_next[1] = _0039_ | _0040_;
  assign _0041_ = s_wyniki[18] & _0019_;
  assign _0042_ = reg_argA[2] & _0020_;
  assign s_argA_next[2] = _0041_ | _0042_;
  assign _0043_ = s_wyniki[19] & _0019_;
  assign _0044_ = reg_argA[3] & _0020_;
  assign s_argA_next[3] = _0043_ | _0044_;
  assign _0045_ = s_inter & _0019_;
  assign _0046_ = _0016_ & _0017_;
  assign s_state_next[0] = _0045_ | _0046_;
  assign s_state_next[1] = s_watchdog_we | _0019_;
  assign s_state_next[2] = s_state[0] & _0018_;
  assign s_transfer = s_wrt | s_state_next[1];
  assign o_miso = s_bit & s_state_next[1];
  assign _0047_ = s_flags[0] & s_state_next[2];
  assign _0048_ = reg_flags[0] & _0017_;
  assign _0049_ = s_wyniki[0] & _0019_;
  assign _0050_ = _0048_ | _0049_;
  assign s_flags_next[0] = _0047_ | _0050_;
  assign _0051_ = s_flags[1] & s_state_next[2];
  assign _0052_ = reg_flags[1] & _0017_;
  assign _0053_ = s_wyniki[1] & _0019_;
  assign _0054_ = _0052_ | _0053_;
  assign s_flags_next[1] = _0051_ | _0054_;
  assign _0055_ = s_flags[2] & s_state_next[2];
  assign _0056_ = reg_flags[2] & _0017_;
  assign _0057_ = s_wyniki[2] & _0019_;
  assign _0058_ = _0056_ | _0057_;
  assign s_flags_next[2] = _0055_ | _0058_;
  assign _0059_ = s_flags[3] & s_state_next[2];
  assign _0060_ = reg_flags[3] & _0017_;
  assign _0061_ = s_wyniki[3] & _0019_;
  assign _0062_ = _0060_ | _0061_;
  assign s_flags_next[3] = _0059_ | _0062_;
  assign _0063_ = s_results[0] & s_state_next[2];
  assign _0064_ = reg_results[0] & _0017_;
  assign _0065_ = s_wyniki[4] & _0019_;
  assign _0066_ = _0064_ | _0065_;
  assign s_results_next[0] = _0063_ | _0066_;
  assign _0067_ = s_wyniki[5] & _0019_;
  assign _0068_ = reg_results[1] & _0017_;
  assign _0069_ = s_results[1] & s_state_next[2];
  assign _0070_ = _0068_ | _0069_;
  assign s_results_next[1] = _0067_ | _0070_;
  assign _0071_ = s_results[2] & s_state_next[2];
  assign _0072_ = reg_results[2] & _0017_;
  assign _0073_ = s_wyniki[6] & _0019_;
  assign _0074_ = _0072_ | _0073_;
  assign s_results_next[2] = _0071_ | _0074_;
  assign _0075_ = s_wyniki[7] & _0019_;
  assign _0076_ = reg_results[3] & _0017_;
  assign _0077_ = s_results[3] & s_state_next[2];
  assign _0078_ = _0076_ | _0077_;
  assign s_results_next[3] = _0075_ | _0078_;
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_flags[0] <= 0;
    else
      reg_flags[0] <= s_flags_next[0];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_flags[1] <= 0;
    else
      reg_flags[1] <= s_flags_next[1];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_flags[2] <= 0;
    else
      reg_flags[2] <= s_flags_next[2];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_flags[3] <= 0;
    else
      reg_flags[3] <= s_flags_next[3];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_results[0] <= 0;
    else
      reg_results[0] <= s_results_next[0];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_results[1] <= 0;
    else
      reg_results[1] <= s_results_next[1];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_results[2] <= 0;
    else
      reg_results[2] <= s_results_next[2];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_results[3] <= 0;
    else
      reg_results[3] <= s_results_next[3];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_oper[0] <= 0;
    else
      reg_oper[0] <= s_oper_next[0];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_oper[1] <= 0;
    else
      reg_oper[1] <= s_oper_next[1];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_oper[2] <= 0;
    else
      reg_oper[2] <= s_oper_next[2];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_oper[3] <= 0;
    else
      reg_oper[3] <= s_oper_next[3];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argB[0] <= 0;
    else
      reg_argB[0] <= s_argB_next[0];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argB[1] <= 0;
    else
      reg_argB[1] <= s_argB_next[1];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argB[2] <= 0;
    else
      reg_argB[2] <= s_argB_next[2];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argB[3] <= 0;
    else
      reg_argB[3] <= s_argB_next[3];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argA[0] <= 0;
    else
      reg_argA[0] <= s_argA_next[0];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argA[1] <= 0;
    else
      reg_argA[1] <= s_argA_next[1];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argA[2] <= 0;
    else
      reg_argA[2] <= s_argA_next[2];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      reg_argA[3] <= 0;
    else
      reg_argA[3] <= s_argA_next[3];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      s_bit <= 0;
    else
      s_bit <= s_bit_next;
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      s_state[0] <= 1;
    else
      s_state[0] <= s_state_next[0];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      s_state[1] <= 1;
    else
      s_state[1] <= s_state_next[1];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      s_state[2] <= 1;
    else
      s_state[2] <= s_state_next[2];
  always @(negedge i_sclk or negedge i_rst)
    if (!i_rst)
      s_state[3] <= 1;
    else
      s_state[3] <= 1'h0;
  assign _0163_ = ~\exe_unit1.i_argA [0];
  assign _0164_ = ~\exe_unit1.i_oper [1];
  assign _0165_ = ~\exe_unit1.i_oper [0];
  assign _0166_ = ~\exe_unit1.i_oper [3];
  assign _0167_ = ~\exe_unit1.i_oper [2];
  assign _0168_ = ~\exe_unit1.i_argA [1];
  assign _0169_ = ~\exe_unit1.i_argA [2];
  assign \exe_unit1.o_PF [0] = ~\exe_unit1.NF [0];
  assign \exe_unit1.o_PF [1] = ~\exe_unit1.NF [1];
  assign _0170_ = _0166_ & _0167_;
  assign _0171_ = _0164_ & _0165_;
  assign _0172_ = _0170_ & _0171_;
  assign _0173_ = \exe_unit1.i_oper [3] & \exe_unit1.i_oper [2];
  assign _0174_ = \exe_unit1.i_oper [1] & _0173_;
  assign _0175_ = _0172_ | _0174_;
  assign _0176_ = _0163_ & \exe_unit1.i_argB [0];
  assign _0177_ = \exe_unit1.i_argA [0] ^ \exe_unit1.i_argB [0];
  assign _0178_ = _0175_ & _0177_;
  assign _0179_ = \exe_unit1.i_argA [0] | \exe_unit1.i_argB [0];
  assign _0180_ = ~_0179_;
  assign _0181_ = \exe_unit1.i_oper [1] & _0165_;
  assign _0182_ = _0170_ & _0181_;
  assign _0183_ = _0180_ & _0182_;
  assign _0184_ = \exe_unit1.i_oper [1] & \exe_unit1.i_oper [0];
  assign _0185_ = _0166_ & \exe_unit1.i_oper [2];
  assign _0186_ = _0184_ & _0185_;
  assign _0187_ = \exe_unit1.ones_counter [0] & _0186_;
  assign _0188_ = _0183_ | _0187_;
  assign _0189_ = _0178_ | _0188_;
  assign _0190_ = _0170_ & _0184_;
  assign _0191_ = _0164_ & \exe_unit1.i_oper [0];
  assign _0192_ = _0185_ & _0191_;
  assign _0193_ = _0190_ | _0192_;
  assign _0194_ = \exe_unit1.i_argA [1] & _0193_;
  assign _0195_ = _0189_ | _0194_;
  assign _0196_ = \exe_unit1.i_oper [3] & _0167_;
  assign _0197_ = _0171_ & _0196_;
  assign _0198_ = \exe_unit1.u2_to_u1 [0] & _0197_;
  assign _0199_ = _0173_ & _0191_;
  assign _0200_ = \exe_unit1.o_crc4 [0] & _0199_;
  assign _0201_ = _0198_ | _0200_;
  assign _0202_ = _0191_ & _0196_;
  assign _0203_ = \exe_unit1.gray_to_u2 [0] & _0202_;
  assign _0204_ = _0171_ & _0173_;
  assign _0205_ = \exe_unit1.o_crc3 [0] & _0204_;
  assign _0206_ = _0203_ | _0205_;
  assign _0207_ = _0201_ | _0206_;
  assign _0208_ = _0170_ & _0191_;
  assign _0209_ = _0179_ & _0208_;
  assign _0210_ = _0181_ & _0196_;
  assign _0211_ = \exe_unit1.thermometer_code [0] & _0210_;
  assign _0212_ = _0209_ | _0211_;
  assign _0213_ = _0165_ & _0185_;
  assign _0214_ = \exe_unit1.i_argB [1] & _0213_;
  assign _0215_ = _0184_ & _0196_;
  assign _0083_ = \exe_unit1.thermometer_decode [0] & _0215_;
  assign _0084_ = _0214_ | _0083_;
  assign _0085_ = _0212_ | _0084_;
  assign _0086_ = _0207_ | _0085_;
  assign \exe_unit1.o_result [0] = _0195_ | _0086_;
  assign _0087_ = \exe_unit1.thermometer_code [1] & _0210_;
  assign _0088_ = \exe_unit1.i_argB [2] & _0213_;
  assign _0089_ = _0087_ | _0088_;
  assign _0090_ = \exe_unit1.u2_to_u1 [1] & _0197_;
  assign _0091_ = \exe_unit1.ones_counter [1] & _0186_;
  assign _0092_ = _0090_ | _0091_;
  assign _0093_ = _0089_ | _0092_;
  assign _0094_ = \exe_unit1.i_argA [2] & _0193_;
  assign _0095_ = \exe_unit1.i_argB [1] | \exe_unit1.i_argA [1];
  assign _0096_ = ~_0095_;
  assign _0097_ = _0182_ | _0095_;
  assign _0098_ = _0208_ | _0096_;
  assign _0099_ = _0097_ & _0098_;
  assign _0100_ = _0094_ | _0099_;
  assign _0101_ = _0093_ | _0100_;
  assign _0102_ = \exe_unit1.i_argB [1] ^ \exe_unit1.i_argA [1];
  assign _0103_ = _0176_ | _0102_;
  assign _0104_ = _0176_ ^ _0102_;
  assign _0105_ = _0175_ & _0104_;
  assign _0106_ = \exe_unit1.o_crc4 [1] & _0199_;
  assign _0107_ = \exe_unit1.o_crc3 [1] & _0204_;
  assign _0108_ = _0106_ | _0107_;
  assign _0109_ = \exe_unit1.gray_to_u2 [1] & _0202_;
  assign _0110_ = \exe_unit1.thermometer_decode [1] & _0215_;
  assign _0111_ = _0109_ | _0110_;
  assign _0112_ = _0108_ | _0111_;
  assign _0113_ = _0105_ | _0112_;
  assign \exe_unit1.o_result [1] = _0101_ | _0113_;
  assign _0114_ = \exe_unit1.i_argB [1] | _0168_;
  assign _0115_ = _0103_ & _0114_;
  assign _0116_ = \exe_unit1.i_argB [2] | \exe_unit1.i_argA [2];
  assign _0117_ = ~_0116_;
  assign _0118_ = \exe_unit1.i_argB [2] ^ \exe_unit1.i_argA [2];
  assign _0119_ = _0115_ | _0118_;
  assign _0120_ = _0115_ ^ _0118_;
  assign _0121_ = _0175_ & _0120_;
  assign _0122_ = \exe_unit1.thermometer_decode [2] & _0215_;
  assign _0123_ = \exe_unit1.ones_counter [2] & _0186_;
  assign _0124_ = _0182_ & _0117_;
  assign _0125_ = _0123_ | _0124_;
  assign _0126_ = _0122_ | _0125_;
  assign _0127_ = \exe_unit1.i_argB [3] & _0213_;
  assign _0128_ = \exe_unit1.o_crc4 [2] & _0199_;
  assign _0129_ = _0127_ | _0128_;
  assign _0130_ = \exe_unit1.o_crc3 [2] & _0204_;
  assign _0131_ = \exe_unit1.u2_to_u1 [2] & _0197_;
  assign _0132_ = _0130_ | _0131_;
  assign _0133_ = _0129_ | _0132_;
  assign _0134_ = \exe_unit1.i_argA [3] & _0193_;
  assign _0135_ = \exe_unit1.gray_to_u2 [2] & _0202_;
  assign _0136_ = _0208_ & _0116_;
  assign _0137_ = _0135_ | _0136_;
  assign _0138_ = _0134_ | _0137_;
  assign _0139_ = _0133_ | _0138_;
  assign _0140_ = _0126_ | _0139_;
  assign \exe_unit1.o_result [2] = _0121_ | _0140_;
  assign _0141_ = \exe_unit1.i_argB [2] | _0169_;
  assign _0142_ = _0119_ & _0141_;
  assign _0143_ = \exe_unit1.i_argB [3] | \exe_unit1.i_argA [3];
  assign _0144_ = ~_0143_;
  assign _0145_ = \exe_unit1.i_argB [3] ^ \exe_unit1.i_argA [3];
  assign _0146_ = _0142_ ^ _0145_;
  assign _0147_ = _0175_ & _0146_;
  assign _0148_ = _0182_ & _0144_;
  assign _0149_ = _0208_ & _0143_;
  assign _0150_ = \exe_unit1.gray_to_u2 [3] & _0202_;
  assign _0151_ = _0149_ | _0150_;
  assign _0152_ = _0148_ | _0151_;
  assign _0153_ = _0164_ & _0127_;
  assign _0154_ = \exe_unit1.i_argA [3] & _0190_;
  assign _0155_ = \exe_unit1.thermometer_decode [3] & _0215_;
  assign _0156_ = _0154_ | _0155_;
  assign _0157_ = \exe_unit1.ones_counter [3] & _0186_;
  assign _0158_ = \exe_unit1.u2_to_u1 [3] & _0197_;
  assign _0159_ = _0157_ | _0158_;
  assign _0160_ = _0156_ | _0159_;
  assign _0161_ = _0153_ | _0160_;
  assign _0162_ = _0152_ | _0161_;
  assign \exe_unit1.o_result [3] = _0147_ | _0162_;
  assign _0220_ = \exe_unit1.bf_pointer_main.i_input [2] | \exe_unit1.bf_pointer_main.i_input [3];
  assign _0221_ = \exe_unit1.bf_pointer_main.i_input [1] | \exe_unit1.bf_pointer_main.i_input [0];
  assign _0222_ = _0220_ & _0221_;
  assign _0223_ = ~_0222_;
  assign _0217_ = \exe_unit1.bf_pointer_main.i_input [1] ^ \exe_unit1.bf_pointer_main.i_input [0];
  assign _0218_ = \exe_unit1.bf_pointer_main.i_input [2] ^ \exe_unit1.bf_pointer_main.i_input [3];
  assign _0219_ = _0217_ | _0218_;
  assign \exe_unit1.bf_pointer_main.o_pointer_local [0] = _0223_ & _0219_;
  assign \exe_unit1.crc3_main.o_crc_local [0] = \exe_unit1.crc3_main.i_data [0] & \exe_unit1.crc3_main.i_poly [0];
  assign _0224_ = \exe_unit1.crc3_main.i_poly [0] & \exe_unit1.crc3_main.i_data [1];
  assign _0225_ = \exe_unit1.crc3_main.i_data [0] & \exe_unit1.crc3_main.i_poly [1];
  assign \exe_unit1.crc3_main.o_crc_local [1] = _0224_ ^ _0225_;
  assign _0226_ = \exe_unit1.crc3_main.i_data [0] & \exe_unit1.crc3_main.i_poly [2];
  assign _0227_ = \exe_unit1.crc3_main.i_poly [0] & \exe_unit1.crc3_main.i_data [2];
  assign _0228_ = \exe_unit1.crc3_main.i_data [1] & \exe_unit1.crc3_main.i_poly [1];
  assign _0229_ = _0227_ ^ _0228_;
  assign \exe_unit1.crc3_main.o_crc_local [2] = _0226_ ^ _0229_;
  assign \exe_unit1.crc4_main.o_crc_local [0] = \exe_unit1.crc4_main.i_data [0] & \exe_unit1.crc4_main.i_poly [0];
  assign _0230_ = \exe_unit1.crc4_main.i_poly [0] & \exe_unit1.crc4_main.i_data [1];
  assign _0231_ = \exe_unit1.crc4_main.i_data [0] & \exe_unit1.crc4_main.i_poly [1];
  assign \exe_unit1.crc4_main.o_crc_local [1] = _0230_ ^ _0231_;
  assign _0232_ = \exe_unit1.crc4_main.i_data [0] & \exe_unit1.crc4_main.i_poly [2];
  assign _0233_ = \exe_unit1.crc4_main.i_poly [0] & \exe_unit1.crc4_main.i_data [2];
  assign _0234_ = \exe_unit1.crc4_main.i_data [1] & \exe_unit1.crc4_main.i_poly [1];
  assign _0235_ = _0233_ ^ _0234_;
  assign \exe_unit1.crc4_main.o_crc_local [2] = _0232_ ^ _0235_;
  assign \exe_unit1.gray_to_u2_main.o_result_local [2] = \exe_unit1.gray_to_u2_main.i_gray [2] ^ \exe_unit1.gray_to_u2_main.i_gray [3];
  assign \exe_unit1.gray_to_u2_main.o_result_local [1] = \exe_unit1.gray_to_u2_main.i_gray [1] ^ \exe_unit1.gray_to_u2_main.o_result_local [2];
  assign \exe_unit1.gray_to_u2_main.o_result_local [0] = \exe_unit1.gray_to_u2_main.i_gray [0] ^ \exe_unit1.gray_to_u2_main.o_result_local [1];
  assign _0236_ = \exe_unit1.nf_pointer_main.i_input [2] ^ \exe_unit1.nf_pointer_main.i_input [3];
  assign _0237_ = \exe_unit1.nf_pointer_main.i_input [1] ^ \exe_unit1.nf_pointer_main.i_input [0];
  assign \exe_unit1.nf_pointer_main.o_pointer_local [0] = _0236_ ^ _0237_;
  assign _0238_ = ~\exe_unit1.ones_counter_main.i_argB_local [1];
  assign _0239_ = ~\exe_unit1.ones_counter_main.i_argA_local [2];
  assign _0240_ = \exe_unit1.ones_counter_main.i_argB_local [0] & \exe_unit1.ones_counter_main.i_argA_local [0];
  assign _0241_ = \exe_unit1.ones_counter_main.i_argA_local [1] & _0240_;
  assign _0242_ = ~_0241_;
  assign _0243_ = \exe_unit1.ones_counter_main.i_argB_local [0] | \exe_unit1.ones_counter_main.i_argA_local [0];
  assign _0244_ = \exe_unit1.ones_counter_main.i_argA_local [1] | _0243_;
  assign _0245_ = ~_0244_;
  assign _0246_ = \exe_unit1.ones_counter_main.i_argA_local [1] | _0240_;
  assign _0247_ = _0243_ & _0246_;
  assign _0248_ = ~_0247_;
  assign _0249_ = _0244_ & _0248_;
  assign _0250_ = _0245_ | _0247_;
  assign _0251_ = _0242_ & _0250_;
  assign _0252_ = _0241_ | _0249_;
  assign _0253_ = \exe_unit1.ones_counter_main.i_argB_local [1] & _0252_;
  assign _0254_ = \exe_unit1.ones_counter_main.i_argB_local [1] | _0252_;
  assign _0255_ = _0238_ ^ _0251_;
  assign _0256_ = \exe_unit1.ones_counter_main.i_argA_local [2] & _0255_;
  assign _0257_ = \exe_unit1.ones_counter_main.i_argA_local [2] ^ _0255_;
  assign _0258_ = \exe_unit1.ones_counter_main.i_argB_local [2] & _0257_;
  assign _0259_ = \exe_unit1.ones_counter_main.i_argB_local [2] ^ _0257_;
  assign _0260_ = \exe_unit1.ones_counter_main.i_argA_local [3] & _0259_;
  assign _0261_ = \exe_unit1.ones_counter_main.i_argA_local [3] ^ _0259_;
  assign _0262_ = \exe_unit1.ones_counter_main.i_argB_local [3] & _0261_;
  assign \exe_unit1.ones_counter_main.o_result_local [0] = \exe_unit1.ones_counter_main.i_argB_local [3] ^ _0261_;
  assign _0263_ = _0260_ | _0262_;
  assign _0264_ = \exe_unit1.ones_counter_main.i_argB_local [1] & _0241_;
  assign _0265_ = ~_0264_;
  assign _0266_ = _0247_ | _0253_;
  assign _0267_ = _0265_ & _0266_;
  assign _0268_ = _0256_ | _0258_;
  assign _0269_ = _0267_ ^ _0268_;
  assign \exe_unit1.ones_counter_main.o_result_local [1] = _0263_ ^ _0269_;
  assign _0270_ = _0262_ & _0269_;
  assign _0271_ = _0260_ & _0269_;
  assign _0272_ = _0258_ & _0267_;
  assign _0273_ = _0247_ & _0254_;
  assign _0274_ = _0239_ | _0273_;
  assign _0275_ = \exe_unit1.ones_counter_main.i_argA_local [2] | _0264_;
  assign _0276_ = _0274_ & _0275_;
  assign _0277_ = _0272_ | _0276_;
  assign _0278_ = _0271_ | _0277_;
  assign \exe_unit1.ones_counter_main.o_result_local [3] = _0270_ & _0278_;
  assign \exe_unit1.ones_counter_main.o_result_local [2] = _0270_ ^ _0278_;
  assign _0279_ = ~\exe_unit1.thermometer_code_main.i_thermo [2];
  assign _0280_ = \exe_unit1.thermometer_code_main.i_thermo [1] & _0279_;
  assign \exe_unit1.thermometer_code_main.o_result_local [0] = \exe_unit1.thermometer_code_main.i_thermo [3] | _0280_;
  assign \exe_unit1.thermometer_code_main.o_result_local [1] = \exe_unit1.thermometer_code_main.i_thermo [2] | \exe_unit1.thermometer_code_main.i_thermo [3];
  assign \exe_unit1.thermometer_decoder_main.o_result_local [12] = \exe_unit1.thermometer_decoder_main.i_nkb [3] & \exe_unit1.thermometer_decoder_main.i_nkb [2];
  assign _0281_ = \exe_unit1.thermometer_decoder_main.i_nkb [1] & \exe_unit1.thermometer_decoder_main.i_nkb [3];
  assign _0282_ = \exe_unit1.thermometer_decoder_main.i_nkb [0] & \exe_unit1.thermometer_decoder_main.i_nkb [1];
  assign _0283_ = \exe_unit1.thermometer_decoder_main.i_nkb [2] | _0282_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [11] = \exe_unit1.thermometer_decoder_main.i_nkb [3] & _0283_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [4] = \exe_unit1.thermometer_decoder_main.i_nkb [3] | \exe_unit1.thermometer_decoder_main.i_nkb [2];
  assign _0284_ = \exe_unit1.thermometer_decoder_main.i_nkb [1] | \exe_unit1.thermometer_decoder_main.i_nkb [3];
  assign \exe_unit1.thermometer_decoder_main.o_result_local [6] = \exe_unit1.thermometer_decoder_main.o_result_local [4] & _0284_;
  assign _0285_ = \exe_unit1.thermometer_decoder_main.i_nkb [0] | \exe_unit1.thermometer_decoder_main.i_nkb [1];
  assign \exe_unit1.thermometer_decoder_main.o_result_local [2] = \exe_unit1.thermometer_decoder_main.i_nkb [1] | \exe_unit1.thermometer_decoder_main.o_result_local [4];
  assign \exe_unit1.thermometer_decoder_main.o_result_local [1] = \exe_unit1.thermometer_decoder_main.o_result_local [4] | _0285_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [14] = \exe_unit1.thermometer_decoder_main.i_nkb [1] & \exe_unit1.thermometer_decoder_main.o_result_local [12];
  assign _0286_ = \exe_unit1.thermometer_decoder_main.i_nkb [0] | \exe_unit1.thermometer_decoder_main.i_nkb [3];
  assign \exe_unit1.thermometer_decoder_main.o_result_local [3] = _0282_ | \exe_unit1.thermometer_decoder_main.o_result_local [4];
  assign _0287_ = \exe_unit1.thermometer_decoder_main.i_nkb [2] & _0285_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [5] = \exe_unit1.thermometer_decoder_main.i_nkb [3] | _0287_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [7] = \exe_unit1.thermometer_decoder_main.o_result_local [6] & _0286_;
  assign _0288_ = \exe_unit1.thermometer_decoder_main.i_nkb [3] & _0285_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [9] = \exe_unit1.thermometer_decoder_main.o_result_local [12] | _0288_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [10] = \exe_unit1.thermometer_decoder_main.o_result_local [12] | _0281_;
  assign \exe_unit1.thermometer_decoder_main.o_result_local [13] = \exe_unit1.thermometer_decoder_main.o_result_local [12] & _0285_;
  assign _0295_ = ~\exe_unit1.u2_to_u1_main.i_argA_local [3];
  assign _0289_ = ~\exe_unit1.u2_to_u1_main.i_argA_local [0];
  assign _0290_ = ~\exe_unit1.u2_to_u1_main.i_argA_local [2];
  assign _0291_ = \exe_unit1.u2_to_u1_main.i_argA_local [3] & _0289_;
  assign \exe_unit1.u2_to_u1_main.o_result_local [0] = \exe_unit1.u2_to_u1_main.i_argA_local [3] ^ \exe_unit1.u2_to_u1_main.i_argA_local [0];
  assign _0292_ = \exe_unit1.u2_to_u1_main.i_argA_local [0] | \exe_unit1.u2_to_u1_main.i_argA_local [1];
  assign _0293_ = _0295_ | _0292_;
  assign \exe_unit1.u2_to_u1_main.o_result_local [1] = \exe_unit1.u2_to_u1_main.i_argA_local [1] ^ _0291_;
  assign _0294_ = \exe_unit1.u2_to_u1_main.i_argA_local [2] | _0292_;
  assign \exe_unit1.u2_to_u1_main.o_result_local [2] = _0290_ ^ _0293_;
  assign \exe_unit1.u2_to_u1_main.o_result_local [3] = \exe_unit1.u2_to_u1_main.i_argA_local [3] & _0294_;
  assign _0367_ = ~\shift_out.i_wrt ;
  assign _0368_ = ~\shift_out.i_en ;
  assign _0369_ = \shift_out.s_shifter [1] & _0367_;
  assign _0370_ = \shift_out.i_data [0] & \shift_out.i_wrt ;
  assign _0371_ = \shift_out.s_shifter [0] | \shift_out.i_en ;
  assign _0372_ = _0368_ | _0370_;
  assign _0373_ = _0369_ | _0372_;
  assign \shift_out.s_shifter_next [0] = _0371_ & _0373_;
  assign _0374_ = _0367_ & \shift_out.s_shifter [2];
  assign _0375_ = \shift_out.i_wrt  & \shift_out.i_data [1];
  assign _0376_ = \shift_out.s_shifter [1] | \shift_out.i_en ;
  assign _0377_ = _0368_ | _0375_;
  assign _0378_ = _0374_ | _0377_;
  assign \shift_out.s_shifter_next [1] = _0376_ & _0378_;
  assign _0379_ = _0367_ & \shift_out.s_shifter [3];
  assign _0380_ = \shift_out.i_wrt  & \shift_out.i_data [2];
  assign _0381_ = \shift_out.i_en  | \shift_out.s_shifter [2];
  assign _0382_ = _0368_ | _0380_;
  assign _0383_ = _0379_ | _0382_;
  assign \shift_out.s_shifter_next [2] = _0381_ & _0383_;
  assign _0384_ = _0367_ & \shift_out.s_shifter [4];
  assign _0385_ = \shift_out.i_wrt  & \shift_out.i_data [3];
  assign _0386_ = \shift_out.i_en  | \shift_out.s_shifter [3];
  assign _0387_ = _0368_ | _0385_;
  assign _0388_ = _0384_ | _0387_;
  assign \shift_out.s_shifter_next [3] = _0386_ & _0388_;
  assign _0389_ = _0367_ & \shift_out.s_shifter [5];
  assign _0390_ = \shift_out.i_wrt  & \shift_out.i_data [4];
  assign _0391_ = \shift_out.i_en  | \shift_out.s_shifter [4];
  assign _0392_ = _0368_ | _0390_;
  assign _0393_ = _0389_ | _0392_;
  assign \shift_out.s_shifter_next [4] = _0391_ & _0393_;
  assign _0394_ = _0367_ & \shift_out.s_shifter [6];
  assign _0395_ = \shift_out.i_wrt  & \shift_out.i_data [5];
  assign _0396_ = \shift_out.i_en  | \shift_out.s_shifter [5];
  assign _0397_ = _0368_ | _0395_;
  assign _0296_ = _0394_ | _0397_;
  assign \shift_out.s_shifter_next [5] = _0396_ & _0296_;
  assign _0297_ = _0367_ & \shift_out.s_shifter [7];
  assign _0298_ = \shift_out.i_wrt  & \shift_out.i_data [6];
  assign _0299_ = \shift_out.i_en  | \shift_out.s_shifter [6];
  assign _0300_ = _0368_ | _0298_;
  assign _0301_ = _0297_ | _0300_;
  assign \shift_out.s_shifter_next [6] = _0299_ & _0301_;
  assign _0302_ = _0367_ & \shift_out.s_shifter [8];
  assign _0303_ = \shift_out.i_wrt  & \shift_out.i_data [7];
  assign _0304_ = \shift_out.i_en  | \shift_out.s_shifter [7];
  assign _0305_ = _0368_ | _0303_;
  assign _0306_ = _0302_ | _0305_;
  assign \shift_out.s_shifter_next [7] = _0304_ & _0306_;
  assign _0307_ = _0367_ & \shift_out.s_shifter [9];
  assign _0308_ = \shift_out.i_wrt  & \shift_out.i_data [8];
  assign _0309_ = \shift_out.i_en  | \shift_out.s_shifter [8];
  assign _0310_ = _0368_ | _0308_;
  assign _0311_ = _0307_ | _0310_;
  assign \shift_out.s_shifter_next [8] = _0309_ & _0311_;
  assign _0312_ = _0367_ & \shift_out.s_shifter [10];
  assign _0313_ = \shift_out.i_wrt  & \shift_out.i_data [9];
  assign _0314_ = \shift_out.i_en  | \shift_out.s_shifter [9];
  assign _0315_ = _0368_ | _0313_;
  assign _0316_ = _0312_ | _0315_;
  assign \shift_out.s_shifter_next [9] = _0314_ & _0316_;
  assign _0317_ = _0367_ & \shift_out.s_shifter [11];
  assign _0318_ = \shift_out.i_wrt  & \shift_out.i_data [10];
  assign _0319_ = \shift_out.i_en  | \shift_out.s_shifter [10];
  assign _0320_ = _0368_ | _0318_;
  assign _0321_ = _0317_ | _0320_;
  assign \shift_out.s_shifter_next [10] = _0319_ & _0321_;
  assign _0322_ = _0367_ & \shift_out.s_shifter [12];
  assign _0323_ = \shift_out.i_wrt  & \shift_out.i_data [11];
  assign _0324_ = \shift_out.i_en  | \shift_out.s_shifter [11];
  assign _0325_ = _0368_ | _0323_;
  assign _0326_ = _0322_ | _0325_;
  assign \shift_out.s_shifter_next [11] = _0324_ & _0326_;
  assign _0327_ = _0367_ & \shift_out.s_shifter [13];
  assign _0328_ = \shift_out.i_wrt  & \shift_out.i_data [12];
  assign _0329_ = \shift_out.i_en  | \shift_out.s_shifter [12];
  assign _0330_ = _0368_ | _0328_;
  assign _0331_ = _0327_ | _0330_;
  assign \shift_out.s_shifter_next [12] = _0329_ & _0331_;
  assign _0332_ = _0367_ & \shift_out.s_shifter [14];
  assign _0333_ = \shift_out.i_wrt  & \shift_out.i_data [13];
  assign _0334_ = \shift_out.i_en  | \shift_out.s_shifter [13];
  assign _0335_ = _0368_ | _0333_;
  assign _0336_ = _0332_ | _0335_;
  assign \shift_out.s_shifter_next [13] = _0334_ & _0336_;
  assign _0337_ = _0367_ & \shift_out.s_shifter [15];
  assign _0338_ = \shift_out.i_wrt  & \shift_out.i_data [14];
  assign _0339_ = \shift_out.i_en  | \shift_out.s_shifter [14];
  assign _0340_ = _0368_ | _0338_;
  assign _0341_ = _0337_ | _0340_;
  assign \shift_out.s_shifter_next [14] = _0339_ & _0341_;
  assign _0342_ = _0367_ & \shift_out.s_shifter [16];
  assign _0343_ = \shift_out.i_wrt  & \shift_out.i_data [15];
  assign _0344_ = \shift_out.i_en  | \shift_out.s_shifter [15];
  assign _0345_ = _0368_ | _0343_;
  assign _0346_ = _0342_ | _0345_;
  assign \shift_out.s_shifter_next [15] = _0344_ & _0346_;
  assign _0347_ = _0367_ & \shift_out.s_shifter [17];
  assign _0348_ = \shift_out.i_wrt  & \shift_out.i_data [16];
  assign _0349_ = \shift_out.i_en  | \shift_out.s_shifter [16];
  assign _0350_ = _0368_ | _0348_;
  assign _0351_ = _0347_ | _0350_;
  assign \shift_out.s_shifter_next [16] = _0349_ & _0351_;
  assign _0352_ = _0367_ & \shift_out.s_shifter [18];
  assign _0353_ = \shift_out.i_wrt  & \shift_out.i_data [17];
  assign _0354_ = \shift_out.i_en  | \shift_out.s_shifter [17];
  assign _0355_ = _0368_ | _0353_;
  assign _0356_ = _0352_ | _0355_;
  assign \shift_out.s_shifter_next [17] = _0354_ & _0356_;
  assign _0357_ = _0367_ & \shift_out.s_shifter [19];
  assign _0358_ = \shift_out.i_wrt  & \shift_out.i_data [18];
  assign _0359_ = \shift_out.i_en  | \shift_out.s_shifter [18];
  assign _0360_ = _0368_ | _0358_;
  assign _0361_ = _0357_ | _0360_;
  assign \shift_out.s_shifter_next [18] = _0359_ & _0361_;
  assign _0362_ = _0367_ & \shift_out.i_bit ;
  assign _0363_ = \shift_out.i_wrt  & \shift_out.i_data [19];
  assign _0364_ = \shift_out.i_en  | \shift_out.s_shifter [19];
  assign _0365_ = _0368_ | _0363_;
  assign _0366_ = _0362_ | _0365_;
  assign \shift_out.s_shifter_next [19] = _0364_ & _0366_;
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [0] <= 0;
    else
      \shift_out.s_shifter [0] <= \shift_out.s_shifter_next [0];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [1] <= 0;
    else
      \shift_out.s_shifter [1] <= \shift_out.s_shifter_next [1];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [2] <= 0;
    else
      \shift_out.s_shifter [2] <= \shift_out.s_shifter_next [2];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [3] <= 0;
    else
      \shift_out.s_shifter [3] <= \shift_out.s_shifter_next [3];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [4] <= 0;
    else
      \shift_out.s_shifter [4] <= \shift_out.s_shifter_next [4];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [5] <= 0;
    else
      \shift_out.s_shifter [5] <= \shift_out.s_shifter_next [5];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [6] <= 0;
    else
      \shift_out.s_shifter [6] <= \shift_out.s_shifter_next [6];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [7] <= 0;
    else
      \shift_out.s_shifter [7] <= \shift_out.s_shifter_next [7];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [8] <= 0;
    else
      \shift_out.s_shifter [8] <= \shift_out.s_shifter_next [8];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [9] <= 0;
    else
      \shift_out.s_shifter [9] <= \shift_out.s_shifter_next [9];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [10] <= 0;
    else
      \shift_out.s_shifter [10] <= \shift_out.s_shifter_next [10];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [11] <= 0;
    else
      \shift_out.s_shifter [11] <= \shift_out.s_shifter_next [11];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [12] <= 0;
    else
      \shift_out.s_shifter [12] <= \shift_out.s_shifter_next [12];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [13] <= 0;
    else
      \shift_out.s_shifter [13] <= \shift_out.s_shifter_next [13];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [14] <= 0;
    else
      \shift_out.s_shifter [14] <= \shift_out.s_shifter_next [14];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [15] <= 0;
    else
      \shift_out.s_shifter [15] <= \shift_out.s_shifter_next [15];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [16] <= 0;
    else
      \shift_out.s_shifter [16] <= \shift_out.s_shifter_next [16];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [17] <= 0;
    else
      \shift_out.s_shifter [17] <= \shift_out.s_shifter_next [17];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [18] <= 0;
    else
      \shift_out.s_shifter [18] <= \shift_out.s_shifter_next [18];
  always @(posedge \shift_out.i_clk_p  or negedge \shift_out.i_rst_n )
    if (!\shift_out.i_rst_n )
      \shift_out.s_shifter [19] <= 0;
    else
      \shift_out.s_shifter [19] <= \shift_out.s_shifter_next [19];
  assign _0433_ = _0430_ | _0432_;
  assign _0434_ = _0401_ & _0433_;
  assign _0435_ = \watchdog.i_we  & \watchdog.i_cycles [3];
  assign \watchdog.s_count_next [3] = _0434_ | _0435_;
  assign _0436_ = _0401_ & \watchdog.s_cycles [4];
  assign _0437_ = _0407_ & _0436_;
  assign _0438_ = \watchdog.i_we  & \watchdog.i_cycles [4];
  assign _0439_ = \watchdog.s_count [4] & _0401_;
  assign _0440_ = _0406_ & _0439_;
  assign _0441_ = _0438_ | _0440_;
  assign \watchdog.s_count_next [4] = _0437_ | _0441_;
  assign \watchdog.s_cycles_next [0] = _0414_ | _0416_;
  assign \watchdog.s_cycles_next [1] = _0419_ | _0421_;
  assign \watchdog.s_cycles_next [2] = _0424_ | _0425_;
  assign _0442_ = _0401_ & \watchdog.s_cycles [3];
  assign \watchdog.s_cycles_next [3] = _0435_ | _0442_;
  assign \watchdog.s_cycles_next [4] = _0436_ | _0438_;
  assign _0398_ = ~\watchdog.s_count [3];
  assign _0399_ = ~\watchdog.s_count [0];
  assign _0400_ = ~\watchdog.s_count [4];
  assign _0401_ = ~\watchdog.i_we ;
  assign _0402_ = \watchdog.s_count [1] | \watchdog.s_count [0];
  assign _0403_ = \watchdog.s_count [2] | _0402_;
  assign _0404_ = ~_0403_;
  assign _0405_ = _0398_ & _0404_;
  assign _0406_ = \watchdog.s_count [3] | _0403_;
  assign _0407_ = _0400_ & _0405_;
  assign _0408_ = \watchdog.s_count [4] | _0406_;
  assign _0409_ = \watchdog.s_cycles [1] | \watchdog.s_cycles [0];
  assign _0410_ = \watchdog.s_cycles [3] | \watchdog.s_cycles [4];
  assign _0411_ = _0409_ | _0410_;
  assign _0412_ = \watchdog.s_cycles [2] | _0411_;
  assign _0413_ = _0401_ & _0412_;
  assign \watchdog.o_inter  = _0407_ & _0413_;
  assign _0414_ = \watchdog.i_we  & \watchdog.i_cycles [0];
  assign _0415_ = _0401_ & _0408_;
  assign _0416_ = _0401_ & \watchdog.s_cycles [0];
  assign _0417_ = _0415_ | _0416_;
  assign _0418_ = _0399_ & _0417_;
  assign \watchdog.s_count_next [0] = _0414_ | _0418_;
  assign _0419_ = \watchdog.i_we  & \watchdog.i_cycles [1];
  assign _0420_ = \watchdog.s_count [1] ^ _0399_;
  assign _0421_ = _0401_ & \watchdog.s_cycles [1];
  assign _0422_ = _0415_ | _0421_;
  assign _0423_ = _0420_ & _0422_;
  assign \watchdog.s_count_next [1] = _0419_ | _0423_;
  assign _0424_ = \watchdog.i_we  & \watchdog.i_cycles [2];
  assign _0425_ = _0401_ & \watchdog.s_cycles [2];
  assign _0426_ = _0415_ | _0425_;
  assign _0427_ = \watchdog.s_count [2] & _0402_;
  assign _0428_ = _0404_ | _0427_;
  assign _0429_ = _0426_ & _0428_;
  assign \watchdog.s_count_next [2] = _0424_ | _0429_;
  assign _0430_ = \watchdog.s_count [3] & _0403_;
  assign _0431_ = \watchdog.s_count [4] | \watchdog.s_cycles [3];
  assign _0432_ = _0405_ & _0431_;
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_cycles [0] <= 0;
    else
      \watchdog.s_cycles [0] <= \watchdog.s_cycles_next [0];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_cycles [1] <= 0;
    else
      \watchdog.s_cycles [1] <= \watchdog.s_cycles_next [1];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_cycles [2] <= 0;
    else
      \watchdog.s_cycles [2] <= \watchdog.s_cycles_next [2];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_cycles [3] <= 0;
    else
      \watchdog.s_cycles [3] <= \watchdog.s_cycles_next [3];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_cycles [4] <= 0;
    else
      \watchdog.s_cycles [4] <= \watchdog.s_cycles_next [4];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_count [0] <= 0;
    else
      \watchdog.s_count [0] <= \watchdog.s_count_next [0];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_count [1] <= 0;
    else
      \watchdog.s_count [1] <= \watchdog.s_count_next [1];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_count [2] <= 0;
    else
      \watchdog.s_count [2] <= \watchdog.s_count_next [2];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_count [3] <= 0;
    else
      \watchdog.s_count [3] <= \watchdog.s_count_next [3];
  always @(posedge \watchdog.i_clk_p  or negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n )
      \watchdog.s_count [4] <= 0;
    else
      \watchdog.s_count [4] <= \watchdog.s_count_next [4];
  assign s_argA = 4'h0;
  assign s_argB = 4'h0;
  assign s_oper = 4'h0;
  assign s_state_next[3] = 1'h0;
  assign \shift_out.i_bit  = i_mosi;
  assign \shift_out.i_clk_p  = i_sclk;
  assign \shift_out.i_data  = s_data;
  assign \shift_out.i_en  = s_transfer;
  assign \shift_out.i_rst_n  = i_rst;
  assign \shift_out.i_wrt  = s_wrt;
  assign s_bit_next = \shift_out.o_bit ;
  assign s_wyniki = \shift_out.o_data ;
  assign \shift_out.o_bit  = \shift_out.s_shifter [0];
  assign \shift_out.o_data  = \shift_out.s_shifter ;
  assign \watchdog.i_clk_p  = i_sclk;
  assign \watchdog.i_cycles  = 5'h13;
  assign \watchdog.i_rst_n  = i_rst;
  assign \watchdog.i_we  = s_watchdog_we;
  assign s_inter = \watchdog.o_inter ;
  assign \exe_unit1.i_argA  = reg_argA;
  assign \exe_unit1.i_argB  = reg_argB;
  assign \exe_unit1.i_oper  = reg_oper;
  assign { _0081_, s_flags[1] } = \exe_unit1.o_BF ;
  assign { _0080_, s_flags[2] } = \exe_unit1.o_NF ;
  assign { _0079_, s_flags[3] } = \exe_unit1.o_PF ;
  assign { _0082_, s_flags[0] } = \exe_unit1.o_SF ;
  assign s_results = \exe_unit1.o_result ;
  assign \exe_unit1.o_BF  = \exe_unit1.BF ;
  assign \exe_unit1.o_NF  = \exe_unit1.NF ;
  assign \exe_unit1.o_SF  = \exe_unit1.SF ;
  assign \exe_unit1.ones_counter_main.i_argA_local  = \exe_unit1.i_argA ;
  assign \exe_unit1.ones_counter_main.i_argB_local  = \exe_unit1.i_argB ;
  assign \exe_unit1.ones_counter  = \exe_unit1.ones_counter_main.o_result_local ;
  assign \exe_unit1.ones_counter_main.i  = 32'd4;
  assign \exe_unit1.u2_to_u1_main.i_argA_local  = \exe_unit1.i_argA ;
  assign \exe_unit1.u2_to_u1  = \exe_unit1.u2_to_u1_main.o_result_local ;
  assign \exe_unit1.gray_to_u2_main.i_gray  = \exe_unit1.i_argA ;
  assign \exe_unit1.gray_to_u2  = \exe_unit1.gray_to_u2_main.o_result_local ;
  assign \exe_unit1.gray_to_u2_main.i  = 32'd0;
  assign \exe_unit1.gray_to_u2_main.o_result_local [3] = \exe_unit1.gray_to_u2_main.i_gray [3];
  assign \exe_unit1.thermometer_code_main.i_thermo  = \exe_unit1.i_argA ;
  assign \exe_unit1.thermometer_code  = \exe_unit1.thermometer_code_main.o_result_local ;
  assign \exe_unit1.thermometer_code_main.i  = 32'd4;
  assign \exe_unit1.thermometer_decoder_main.i_nkb  = \exe_unit1.i_argA ;
  assign { _0216_, \exe_unit1.thermometer_decode  } = \exe_unit1.thermometer_decoder_main.o_result_local ;
  assign \exe_unit1.thermometer_decoder_main.i  = 32'd15;
  assign { \exe_unit1.thermometer_decoder_main.o_result_local [8], \exe_unit1.thermometer_decoder_main.o_result_local [0] } = { \exe_unit1.thermometer_decoder_main.i_nkb [3], 1'h1 };
  assign \exe_unit1.crc3_main.i_data  = \exe_unit1.i_argA ;
  assign \exe_unit1.crc3_main.i_poly  = \exe_unit1.i_argB ;
  assign \exe_unit1.o_crc3  = \exe_unit1.crc3_main.o_crc_local ;
  assign \exe_unit1.crc3_main.crc  = 3'h0;
  assign \exe_unit1.crc3_main.crc_tmp  = { 4'hx, \exe_unit1.crc3_main.o_crc_local  };
  assign \exe_unit1.crc3_main.i  = 32'd4294967295;
  assign \exe_unit1.crc3_main.poly_tmp  = \exe_unit1.crc3_main.i_poly [3:1];
  assign \exe_unit1.crc4_main.i_data  = \exe_unit1.i_argA ;
  assign \exe_unit1.crc4_main.i_poly  = \exe_unit1.i_argB ;
  assign \exe_unit1.o_crc4  = \exe_unit1.crc4_main.o_crc_local ;
  assign \exe_unit1.crc4_main.crc  = 3'h0;
  assign \exe_unit1.crc4_main.crc_tmp  = { 4'hx, \exe_unit1.crc4_main.o_crc_local  };
  assign \exe_unit1.crc4_main.i  = 32'd4294967295;
  assign \exe_unit1.crc4_main.poly_tmp  = \exe_unit1.crc4_main.i_poly [3:1];
  assign \exe_unit1.nf_pointer_main.i_input  = \exe_unit1.o_result ;
  assign \exe_unit1.NF  = \exe_unit1.nf_pointer_main.o_pointer_local ;
  assign { \exe_unit1.nf_pointer_main.counter [31:4], \exe_unit1.nf_pointer_main.counter [0] } = { 28'h0000000, \exe_unit1.nf_pointer_main.o_pointer_local [0] };
  assign \exe_unit1.nf_pointer_main.i  = 32'd4;
  assign \exe_unit1.nf_pointer_main.o_pointer_local [1] = 1'h0;
  assign \exe_unit1.sf_pointer_main.i_input  = \exe_unit1.o_result ;
  assign \exe_unit1.SF  = \exe_unit1.sf_pointer_main.o_pointer_local ;
  assign \exe_unit1.sf_pointer_main.o_pointer_local  = { 1'h0, \exe_unit1.sf_pointer_main.i_input [3] };
  assign \exe_unit1.bf_pointer_main.i_input  = \exe_unit1.o_result ;
  assign \exe_unit1.BF  = \exe_unit1.bf_pointer_main.o_pointer_local ;
  assign \exe_unit1.bf_pointer_main.counter [31:4] = 28'h0000000;
  assign \exe_unit1.bf_pointer_main.i  = 32'd4;
  assign \exe_unit1.bf_pointer_main.o_pointer_local [1] = 1'h0;
endmodule
